title: VE2HEW
author: Anthony Di Iorio
email: anthony@ve2hew.com
description: Anthony VE2HEW - Ham Radio Blog

remote_theme: tanilolli/hewin-theme
show_excerpts: true

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag