title: VE2HEW
author: Anthony Di Iorio
email: anthony@ve2hew.com
description: Anthony VE2HEW - Ham Radio Blog

permalink: /:year/:month/:day/:title:output_ext

remote_theme: anthonydiiorio/hewin-theme
show_excerpts: true

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
