title: VE2HEW
author: Anthony Di Iorio
email: anthony@ve2hew.com
description: Anthony VE2HEW - Ham Radio Blog

remote_theme: jekyll/minima
show_excerpts: true

exclude: ["CNAME", "Rakefile", "README.md"]
